import { i18n } from "@/i18n-config";

import { Hind_Siliguri } from "@next/font/google";
import Nav from "../newComponetns/Nav";

import "bootstrap/dist/css/bootstrap.min.css";

import "@/app/styles/app.scss";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import AppLayout from "../layout/AppLayout";
import Container from "@/app/newComponetns/Container";
import Head from "./head";
// import MainSection from "@/components/MainSection";

const hindSiliguri = Hind_Siliguri({
  subsets: ["bengali", "latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export async function generateStaticParams() {
  return i18n.locales.map((locale) => ({ lang: locale }));
}

export default function RootLayout({ children, params }) {
  return (
    <html lang={params.lang}>
      <Head />
      <body className={`${hindSiliguri.className}`}>
        <Nav />

        <Container>{children}</Container>
        {/* <AppLayout>{children}</AppLayout> */}
      </body>
    </html>
  );
}
